[deps]
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
MuJoCo = "1c101251-5e0f-4746-b44c-0728d433b68a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
