[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
MuJoCo_jll = "32af7c3b-80ec-5621-8194-2f6cb2280831"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
UnsafeArrays = "c4a57d5a-5b31-53a6-b365-19f8c011fbd6"


[compat]
MuJoCo_jll = "3.1.6"
